### PR TITLE
Fixed Undo Button Functionality in Query Statement

### PR DESCRIPTION
**Pull request by gablabelle**
Fixed Undo Button Functionality in Query Statement by:
- Preventing undesired state mutations.
- Preventing committing twice the same draft.
- Preventing sorting on non-existing list of elements.
- Allowing undo to also work on the first step (New Query)

### CODE REVIEW

**Comment by nyanofthemoon** [comment]
@gablabelle 
image

**Comment by nyanofthemoon** [comment]
@gablabelle 
Unable to "select all" or "deselect all" checkbox group
image

**Comment by nyanofthemoon** [comment]
@gablabelle 
When "combining" two queries, the resulting composite query does not become the active query.
image

**Comment by nyanofthemoon** [comment]
@gablabelle 
When clicking on the red button to delete a query:
image

**Comment by nyanofthemoon** [comment]
@gablabelle 
Aggregation results and counts for searched values from the input field are not present.
image

**Comment by nyanofthemoon** [comment]
@gablabelle Query result counts are not updated on change.
image

**Comment by nyanofthemoon** [comment]
@gablabelle 
I get an infinite spin when undoing a subquery
image

**Comment by gablabelle** [comment]
> @gablabelle
> Unable to "select all" checkbox group
> image
> Unable to "deselect all" checkbox group
> image

@nyanofthemoon same thing here I'm unable to reproduce. If you could guide me on how to reproduce it would be appreciated thanks.

Screenshot from 2019-10-11 09-03-31

**Comment by gablabelle** [comment]
@nyanofthemoon I've pushed the required fixes, except for the 2 things I couldn't reproduce. If you give me the steps to reproduce it would be appreciated. Thanks for your code review.

**Pull request merged**
